const List<String> cidades = [
  "São João",
  "Garanhuns",
  "Angelim",
  "Canhotinho",
  "Caetés",
  "Calçado",
  "Jupi",
  "Brejão",
  "Lajedo",
  "Paranatama",
  "Jurema",
  "Jucati",
  "Capoeiras",
  "Palmeirina",
  "Correntes",
  "Lagoa do Ouro",
  "Bom Conselho",
  "Iatí",
  "Saloá",
  "Terezinha",
];

const List<List> ligacoesCidade = [
  ["Garanhuns", "São João", 16],
  ["Garanhuns", "Caetés", 19],
  ["Garanhuns", "Paranatama", 21],
  ["Garanhuns", "Jupi", 23],
  ["Garanhuns", "Brejão", 24],
  ["Lajedo", "Jupi", 13],
  ["Lajedo", "Calçado", 14],
  ["Lajedo", "Canhotinho", 32],
  ["São João", "Angelim", 11],
  ["São João", "Calçado", 18],
  ["Calçado", "Jupi", 13],
  ["Calçado", "Canhotinho", 30],
  ["Angelim", "Canhotinho", 12],
  ["Jurema", "Calçado", 29],
  ["Jurema", "Canhotinho", 39],
  ["Jurema", "Lajedo", 30],
  ["Jucati", "Jupi", 10],
  ["Jucati", "Capoeiras", 18],
  ["Caetés", "Capoeiras", 6],
  ["Palmeirina", "Angelim", 17],
  ["Palmeirina", "Garanhuns", 41],
  ["Palmeirina", "Correntes", 24],
  ["Palmeirina", "Lagoa do Ouro", 27],
  ["Correntes", "Lagoa do Ouro", 16],
  ["Lagoa do Ouro", "Brejão", 47],
  ["Lagoa do Ouro", "Bom Conselho", 33],
  ["Bom Conselho", "Terezinha", 18],
  ["Bom Conselho", "Iatí", 26],
  ["Terezinha", "Brejão", 8.8],
  ["Terezinha", "Saloá", 17],
  ["Saloá", "Paranatama", 15],
  ["Iatí", "Paranatama", 36],
];
